// Configs dos painéis de cenários (decisão) do pleno. Cada `src` define CFG.
export const CENARIOS = [
{
  file: "clima-decisao", frag: "condições climáticas",
  titulo: "Clima, Armazenamento & Go/No-Go",
  src: `CFG={ title:"Clima — Go / No-Go", sub:"Leia as condições e decida disparar ou segurar. Segurança vem antes do show.", pass:80,
    passMsg:"Decisões climáticas no ponto — é isso que evita acidente e cancelamento.", scen:[
    { tag:"Vento", sit:"Show ao ar livre. Você vai disparar SHELLS AÉREOS (F3). O anemômetro marca:",
      data:[["Vento","46 km/h","bad"],["Rajadas","até 60","bad"],["Chuva","não","ok"]],
      opts:[{t:"Disparar — está seco",ok:false},{t:"HOLD — vento acima do limite, área de queda imprevisível",ok:true},{t:"Disparar só metade",ok:false}],
      why:"Vento forte joga a fallout (queijo/estrelas e detritos) fora da área de queda planejada. As normas definem vento máximo (tipicamente ~30–40 km/h para aéreos). Acima disso: <b>HOLD</b> e reavaliar." },
    { tag:"Chuva", sit:"Começou uma garoa fina sobre os morteiros e gerbs externos, sem cobertura.",
      data:[["Chuva","garoa","warn"],["Umidade","92%","warn"],["Vento","10 km/h","ok"]],
      opts:[{t:"Disparar rápido antes de molhar mais",ok:false},{t:"HOLD, cobrir/impermeabilizar e checar continuidade",ok:true}],
      why:"Umidade compromete a pólvora e os e-matches — falha de ignição (misfire) e disparos parciais. Proteja o material, seque, refaça o teste de continuidade. Pirotecnia molhada não dispara com segurança." },
    { tag:"Interno", sit:"Casamento em salão coberto. Efeito pedido: FAÍSCA FRIA (cold spark) na entrada dos noivos.",
      data:[["Local","interno","ok"],["Pé-direito","6 m","ok"],["Sprinkler","sim","warn"]],
      opts:[{t:"GO — efeito frio, seguindo distância e sem tecido por perto",ok:true},{t:"HOLD — fogo é proibido em local fechado",ok:false}],
      why:"Faísca fria é efeito FRIO (F1), liberado perto do público em interno — desde que respeitada a distância e afastado de tecidos. Atenção: a coluna pode acionar detector de fumaça/sprinkler; alinhe com o local antes." },
    { tag:"Tempestade", sit:"Nuvem de tempestade se aproxima; primeiros raios ao longe. Há torres de som e rigging metálico.",
      data:[["Raios","aproximando","bad"],["Vento","sobe rápido","bad"]],
      opts:[{t:"Continuar o show até chover",ok:false},{t:"HOLD tudo, plano de tempestade e desmobilizar pessoal de estruturas altas",ok:true}],
      why:"Raio é risco de morte em torres/rigging. Acione o plano de tempestade: interromper, tirar pessoal das estruturas metálicas e aguardar a regra de segurança (ex.: 30 min após o último raio) antes de retomar." },
    { tag:"Armazenamento", sit:"No paiol, uma caixa de artefatos ficou exposta e está com a base úmida/manchada.",
      data:[["Material","úmido","bad"],["Validade","ok","ok"]],
      opts:[{t:"Usar mesmo, secando no sol",ok:false},{t:"Segregar, não usar e destinar conforme a norma/fabricante",ok:true}],
      why:"Artefato com suspeita de umidade/deterioração vira imprevisível (misfire ou queima anormal). Nunca improvise secagem. Segregue, identifique e destine conforme fabricante/legislação. Armazenamento seco, ventilado e afastado de ignição é regra." },
    { tag:"Calor", sit:"Dia muito quente; cilindros de CO₂ ao sol, pressão subindo no manômetro.",
      data:[["Temp.","39 °C","warn"],["Pressão cilindro","alta","warn"]],
      opts:[{t:"Ignorar, CO₂ não pega fogo",ok:false},{t:"Sombrear/refrescar os cilindros e conferir válvula de alívio",ok:true}],
      why:"CO₂ não é inflamável, mas cilindro superaquecido = pressão perigosa. Mantenha à sombra, ventilado, com válvula de alívio operante e bem fixado. Nunca deixe cilindro pressurizado exposto ao sol direto por horas." },
  ] }`
},
{
  file: "legislacao-decisao", frag: "legislação",
  titulo: "Legislação & Licenças (Brasil)",
  src: `CFG={ title:"Legislação — Pirotecnia no Brasil", sub:"Quem fiscaliza, o que precisa e qual categoria. Documentação é parte do trabalho.", pass:80,
    passMsg:"Base legal dominada — é o que separa o profissional do improviso.", scen:[
    { tag:"Fiscalização", sit:"Quem controla a fabricação, o comércio e o uso de produtos explosivos (fogos/pirotecnia) no Brasil?",
      data:[],
      opts:[{t:"O Exército Brasileiro (produtos controlados — R-105)",ok:true},{t:"A ANATEL",ok:false},{t:"Apenas a prefeitura",ok:false}],
      why:"Explosivos e fogos são <b>Produtos Controlados pelo Exército</b> (regidos pelo R-105). Fabricação, comércio, transporte e uso profissional passam por essa fiscalização — além de Corpo de Bombeiros e órgãos locais." },
    { tag:"Show externo", sit:"Espetáculo com SHELLS AÉREOS (F3/F4) num festival. O que é indispensável?",
      data:[],
      opts:[{t:"Blaster credenciado + licenças (Exército/Bombeiros) + ART + plano de tiro",ok:true},{t:"Só a nota fiscal dos fogos",ok:false},{t:"Autorização verbal do produtor",ok:false}],
      why:"Pirotecnia profissional (F3/F4) exige responsável técnico habilitado (blaster credenciado), licenças dos órgãos competentes, <b>ART</b> (responsabilidade técnica), plano de tiro e vistoria do Corpo de Bombeiros/AVCB do evento." },
    { tag:"Categorias", sit:"A classificação de fogos por categoria (F1 a F4) serve para:",
      data:[["F1","baixo risco","ok"],["F4","só profissional","bad"]],
      opts:[{t:"Definir risco, distância mínima e quem pode manusear",ok:true},{t:"Definir só a cor do efeito",ok:false},{t:"Nada, é comercial",ok:false}],
      why:"A categoria define o <b>risco, a distância de segurança e a habilitação</b> exigida. F1 = baixo risco (interno); F4 = alto, uso exclusivo de profissionais habilitados, ao ar livre e com grandes afastamentos." },
    { tag:"Efeito frio", sit:"Uma faísca fria (cold spark) é vendida como 'não é fogo de artifício'. No evento você:",
      data:[["Categoria","efeito frio / F1","ok"]],
      opts:[{t:"Ainda segue plano de segurança, distância e o AVCB do local",ok:true},{t:"Ignora qualquer regra, é seguro",ok:false}],
      why:"Mesmo sendo efeito frio e de baixa restrição, um profissional segue plano de segurança, distâncias, afastamento de materiais inflamáveis e as regras do local (AVCB/Bombeiros). Segurança não depende só da categoria." },
    { tag:"Responsabilidade", sit:"O documento que formaliza quem é o responsável técnico pela execução é a:",
      data:[],
      opts:[{t:"ART (Anotação de Responsabilidade Técnica)",ok:true},{t:"Certidão de nascimento",ok:false},{t:"Nota fiscal",ok:false}],
      why:"A <b>ART</b> vincula um responsável técnico habilitado ao serviço — é exigida em projetos/execuções de pirotecnia profissional e responsabiliza legalmente quem assina." },
    { tag:"Transporte", sit:"Levar os artefatos até o local do show envolve:",
      data:[["Produto","controlado","warn"]],
      opts:[{t:"Regras de transporte de produto perigoso/controlado (ANTT/Exército)",ok:true},{t:"Qualquer carro serve",ok:false}],
      why:"Transporte de fogos = produto perigoso/controlado: segue normas específicas (ANTT/Exército), acondicionamento correto, documentação e veículo adequado. Improviso aqui é crime e risco grave." },
  ] }`
},
{
  file: "comunicacao-decisao", frag: "comunicação",
  titulo: "Comunicação & Jargões",
  src: `CFG={ title:"Comunicação — Rádio & Jargões", sub:"O jargão certo evita disparo errado. Clareza salva o show (e vidas).", pass:80,
    passMsg:"Comunicação profissional — é o que mantém a equipe sincronizada e segura.", scen:[
    { tag:"Standby", sit:"No rádio você ouve: “Standby cue 5”. Isso significa:",
      data:[],
      opts:[{t:"Prepare-se: a cue 5 vai disparar em breve, aguarde o comando",ok:true},{t:"Dispare a cue 5 agora",ok:false},{t:"Cancele a cue 5",ok:false}],
      why:"“Standby” = <b>fique pronto e atento</b>, o comando vem a seguir. Só dispara no “GO”. Confundir standby com GO é uma das causas clássicas de disparo fora de hora." },
    { tag:"Abortar", sit:"Segundos antes de uma cue pirotécnica, você vê pessoas invadindo a zona de exclusão. No rádio, você diz:",
      data:[["Área","invadida","bad"]],
      opts:[{t:"“HOLD FIRE, HOLD FIRE — área não liberada”",ok:true},{t:"Nada, dispara mesmo assim",ok:false},{t:"“Standby”",ok:false}],
      why:"“<b>Hold fire</b>” é o comando universal de abortar/segurar o disparo. Dito com clareza e repetido. Qualquer um da equipe de segurança pode e deve chamar hold fire ao ver risco." },
    { tag:"Confirmação", sit:"Você recebe uma instrução e responde “Cópia” (copy). Isso quer dizer:",
      data:[],
      opts:[{t:"Entendido / recebi a mensagem",ok:true},{t:"Discordo",ok:false},{t:"Repita",ok:false}],
      why:"“Cópia/Copy” = <b>recebido e entendido</b>. Confirmar o recebimento fecha o loop de comunicação — quem manda sabe que a mensagem chegou." },
    { tag:"GO", sit:"Quem dá o comando final de “GO” para uma cue pirotécnica?",
      data:[],
      opts:[{t:"O operador/stage manager conforme o roteiro, com a segurança confirmada",ok:true},{t:"Qualquer pessoa da plateia",ok:false},{t:"O DJ",ok:false}],
      why:"O “GO” sai de quem coordena (operador/SM) seguindo o cue sheet e SÓ com a confirmação de área/segurança. Cadeia de comando clara evita disparo por engano. Na dúvida: hold." },
    { tag:"Contagem", sit:"A sequência correta imediatamente antes de um disparo pirotécnico manual é:",
      data:[],
      opts:[{t:"Confirmar área livre → armar → contagem → GO",ok:true},{t:"GO → armar → conferir",ok:false},{t:"Armar → GO → conferir área",ok:false}],
      why:"Ordem que salva: <b>área livre → armar → contagem/standby → GO</b>. Armar só depois da área confirmada; o GO é o último passo. Nunca armar/disparar antes de garantir que ninguém está na zona de risco." },
    { tag:"Rádio", sit:"Boas práticas de rádio durante o show incluem:",
      data:[],
      opts:[{t:"Falar curto e claro, um por vez, confirmar recebimento",ok:true},{t:"Falar tudo junto e brincar no canal",ok:false}],
      why:"Canal limpo: mensagens curtas, uma pessoa por vez, jargão padrão e confirmação. O canal de disparo não é para conversa — ruído no rádio na hora errada custa caro." },
  ] }`
},
{
  file: "documentacao-decisao", frag: "documentação",
  titulo: "Documentação & Rider Técnico",
  src: `CFG={ title:"Documentação & Rider Técnico", sub:"O papel também faz o show acontecer com segurança e sem multa.", pass:80,
    passMsg:"Documentação em ordem — é o que garante o acesso, a segurança e o cachê.", scen:[
    { tag:"Rider", sit:"O rider técnico de efeitos serve para:",
      data:[],
      opts:[{t:"Especificar equipamentos, energia, rigging, distâncias e necessidades da produção",ok:true},{t:"Listar o repertório da banda",ok:false},{t:"Nada, é opcional",ok:false}],
      why:"O <b>rider técnico</b> comunica à produção tudo que o efeito precisa: equipamentos, pontos de energia, rigging, distâncias de segurança, pessoal e tempos. Rider claro = montagem sem surpresa." },
    { tag:"Licença", sit:"Faltando 2 dias para um show com pirotecnia F3, você percebe que não saiu a licença do Corpo de Bombeiros. Você:",
      data:[["Licença Bombeiros","pendente","bad"]],
      opts:[{t:"Aciona a produção imediatamente; sem licença, a pirotecnia não acontece",ok:true},{t:"Dispara mesmo assim",ok:false}],
      why:"Sem licença/vistoria, a pirotecnia <b>não pode ocorrer</b> — risco legal e de segurança. Documentação é caminho crítico: acompanhe prazos e escale cedo. Melhor um show sem pirotecnia do que um show ilegal e inseguro." },
    { tag:"Cue sheet", sit:"O cue sheet (roteiro técnico) do show serve para:",
      data:[],
      opts:[{t:"Definir cada efeito, seu momento (timecode) e o canal de disparo",ok:true},{t:"Só decorar o camarim",ok:false}],
      why:"O <b>cue sheet</b> é a partitura dos efeitos: o quê, quando (timecode/deixa) e por qual canal. É ensaiado na passagem e conferido contra o patch da maleta — cada efeito no seu botão." },
    { tag:"Checklist", sit:"Antes de liberar o disparo, o checklist pré-show deve incluir:",
      data:[],
      opts:[{t:"Área isolada, extintor no posto, continuidade testada, equipe informada",ok:true},{t:"Só ligar a maleta",ok:false}],
      why:"Checklist pré-show: <b>área/distâncias, EPI, extintor e brigada, teste de continuidade, patch conferido e equipe/segurança avisada</b>. Item crítico em falta = não dispara." },
    { tag:"Registro", sit:"Guardar as licenças, ART, plano de tiro e checklist assinados serve para:",
      data:[],
      opts:[{t:"Comprovar conformidade e proteger você juridicamente",ok:true},{t:"Enfeitar a pasta",ok:false}],
      why:"O dossiê documental comprova que tudo foi feito conforme a norma — protege o profissional e a produção em fiscalização ou incidente. Documentar é parte do ofício, não burocracia inútil." },
  ] }`
},
];
