// Auto-generated by scripts/adapt-notaon.mjs — do not edit.
import type { ComponentType } from "react";

export type NotaonCapLoader = () => Promise<{ default: ComponentType }>;
export type NotaonSubjectReg = Record<number, NotaonCapLoader>;

export const NOTAON_LOADERS: Record<string, () => Promise<{ default: NotaonSubjectReg }>> = {
  biologia: () => import("./biologia"),
  espanhol: () => import("./espanhol"),
  filosofia: () => import("./filosofia"),
  fisica: () => import("./fisica"),
  geografia: () => import("./geografia"),
  historia: () => import("./historia"),
  ingles: () => import("./ingles"),
  matematica: () => import("./matematica"),
  portugues: () => import("./portugues"),
  quimica: () => import("./quimica"),
  redacao: () => import("./redacao"),
  sociologia: () => import("./sociologia"),
};
